### ISSUE TITLE
Commands are not listed by bin/magento for M2.4.1

### ISSUE THREAD

**Issue by shochdoerfer** [semaio/Magento2-ConfigImportExport#40]
### General

* Module version: 3.3.0
* Magento version: 2.4.1
* PHP version: 7.4

### Issue description

I created a new Magento 2.4.1 project and installed the `semaio/magento2-configimportexport` package afterward as described in the README file. When invoking `bin/magento` the commands exposed by the module are not listed and I cannot invoke them.

I could track things down to this:
Currently, the module is registering the commands with type `Magento\Framework\Console\CommandList`. When changing the type to `Magento\Framework\Console\CommandListInterface` the commands appear when invoking `bin/magento` .

This is also mentioned in the README file of the Console package: https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/Console/README.md

Happy to provide a PR if changing the type makes sense for you.

**Comment by ktomk** [comment]
Do you know if using the interface is backwards compatible to earlier Magento versions? @shochdoerfer

**Comment by shochdoerfer** [comment]
The mentioned README.md file was last changed in April 2016 so I would assume the interface is available for quite a while now. The first commit for`Magento\Framework\Console\CommandListInterface`  occurred in Sep 2015.

I could not really track a PR that changed the behaviour, at least no PR that explicitly states the change. The closest one seems this https://github.com/magento/magento2/pull/29762

**Comment by therouv** [comment]
@shochdoerfer Happy to merge a PR for this if it's backwards compatible. Otherwise I'd set up separate release branches.

**Comment by shochdoerfer** [comment]
@therouv sure, need to investigate. The issue was rather opened to see if I am doing something wrong or if other people ran in the same situation :)

**Comment by therouv** [comment]
@shochdoerfer I've changed it accordingly since Magento has a static test which discourages this behavior (see [here](https://github.com/magento/magento2/blob/fbfac3e51730abe2b79c6072544bc9742fcf7606/dev/tests/static/testsuite/Magento/Test/Legacy/Magento/Framework/ObjectManager/DiConfigTest.php#L68)).

However, I've tested with all 2.4 versions and the commands were always displayed without any issues:

![configimportexport-command-list-m241](https://user-images.githubusercontent.com/393419/111039503-aa922a80-842e-11eb-8cc4-dbe237e3539b.png)

**Comment by shochdoerfer** [comment]
Awesome! Thanks. Sorry, lost track of this issue ;(
